name: 'Setup Tools'
description: 'Cleans the workspace after the workflow'
inputs:
  post-clean:
    description: whether to clean the workspace in a post-step
    required: false

  python-version:
    description: python version
    required: false

  node-version:
    description: node version
    required: false

  java-version:
    description: java version
    required: false
  java-distribution:
    default: temurin
    description: java distribution
    required: false

  maven-version: # 3.8.6
    description: maven version
    required: false

  jfrog-cli-version:
    description: jfrog cli version
    required: false
  jfrog-url:
    description: jfrog url (just base URL, without any path)
    required: false
    default: https://artifacts.i.mercedes-benz.com
  jfrog-user:
    description: jfrog user
    required: false
  jfrog-password:
    description: jfrog password / API key
    required: false

  gh-cli-version: # 2.14.6
    description: gh cli version
    required: false

  sops-version:
    description: sops version
    required: false
  gpg-private-key:
    description: gpg private key
    required: false
  gpg-passphrase:
    description: gpg passphrase
    required: false
  ssh-private-key:
    description: ssh private key
    required: false

  kube-setup-tools:
    default: |
      kustomize
    description: |
      newline-separated list of tools to set up.
      supported by this action: kubectl, kustomize, helm, yq
      supported if this action is adapted: kubeval, conftest, rancher, tilt, skaffold, kube-score
    required: false
  kubectl-version: # 1.24.3
    description: java version
    required: false
  kustomize-version: # 4.5.7
    description: java version
    required: false
  helm-version: # 3.9.4
    description: helm version
    required: false
  yq-version: # 4.27.2
    description: yq version
    required: false

  terraform-version:
    description: terraform version
    required: false

  coverity-version:
    description: coverity version
    required: false
  coverity-auth-file:
    description: content of coverity auth file
    required: false
  coverity-configure-language:
    description: language that coverity should be configured with (such as java)
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'configure: clean workspace after workflow'  # put this at start so the "Post" is coming at the very last
      if: inputs.post-clean == 'true'
      uses: ./workflows/actions/clean-workspace-post

    - name: 'setup: python'
      uses: actions/setup-python@v3
      if: inputs.python-version != ''
      with:
        python-version: ${{ inputs.python-version }}

    - name: 'setup: terraform'
      uses: hashicorp/setup-terraform@v2
      if: inputs.terraform-version != ''
      with:
        terraform-version: ${{ inputs.terraform-version }}

    - name: 'setup: node'
      if: inputs.node-version != ''
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: 'setup: java'
      if: inputs.java-version != ''
      uses: actions/setup-java@v3.1.1
      with:
        overwrite-settings: false
        java-version: ${{ inputs.java-version }}
        check-latest: false # TODO reactivate, azure issue https://git.i.mercedes-benz.com/CIAM-Me-Identity/ciam-dummy-notifications/runs/1542644?check_suite_focus=true
        distribution: ${{ inputs.java-distribution }}

    - name: 'setup: maven'
      if: inputs.maven-version != ''
      uses: stCarolas/setup-maven@417e1a9899611c0350621d1fb0c2770f35105c69
      with:
        maven-version: ${{ inputs.maven-version }}

    - name: 'setup: sops'
      uses: mdgreenwald/mozilla-sops-action@6a613a84888faf93848b0327954b50106043c4fe # v1.1.0
      if: inputs.sops-version != ''
      with:
        version: ${{ inputs.sops-version }}

    - name: 'init: gpg'
      if: inputs.gpg-private-key != ''
        && inputs.gpg-passphrase != ''
      uses: crazy-max/ghaction-import-gpg@e00cb83a68c1158b29afc5217dd0582cada6d172 # v4.4.0
      with:
        gpg_private_key: ${{ inputs.gpg-private-key }}
        passphrase: ${{ inputs.gpg-passphrase }}

    - name: 'init: ssh-agent'
      if: inputs.ssh-private-key != ''
      uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd # v0.5.4
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: 'setup: kube-tools'
      uses: yokawasa/action-setup-kube-tools@af83f4b560dbd295218ef760840d835918a69453
      if: inputs.kubectl-version != ''
        || inputs.kustomize-version != ''
        || inputs.helm-version != ''
        || inputs.yq-version != ''
      with:
        setup-tools: ${{ inputs.kube-setup-tools }}
        kubectl: ${{ inputs.kubectl-version }}
        kustomize: ${{ inputs.kustomize-version }}
        helm: ${{ inputs.helm-version }}
        yq: ${{ inputs.yq-version }}

    - name: 'setup: jfrog cli'
      if: inputs.jfrog-cli-version != ''
        && inputs.jfrog-url != ''
        && inputs.jfrog-user != ''
        && inputs.jfrog-password != ''
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: ${{ inputs.jfrog-url }}
        JF_USER: ${{ inputs.jfrog-user }}
        JF_PASSWORD: ${{ inputs.jfrog-password }}
      with:
        version: ${{ inputs.jfrog-cli-version }}

    - name: 'setup: gh cli'
      if: inputs.gh-cli-version != ''
      uses: ./workflows/actions/setup-gh-cli
      with:
        gh-cli-version: ${{ inputs.gh-cli-version }}

    - name: 'setup: coverity'
      if: inputs.coverity-auth-file != ''
      uses: ./workflows/actions/setup-coverity
      with:
        coverity-version: ${{ inputs.coverity-version }}
        coverity-auth-file: ${{ inputs.coverity-auth-file }}
        configure-language: ${{ inputs.coverity-configure-language }}
